### ISSUE TITLE
As a developer I need example images of slide sheets

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/sled#1]

**Comment by tmcelrath** [comment]
![1_rack](https://user-images.githubusercontent.com/11411328/57935106-ad4d8400-7886-11e9-903d-8fd87148cebc.jpg)

**Comment by tmcelrath** [comment]
![S081_1](https://user-images.githubusercontent.com/11411328/57935225-f1d91f80-7886-11e9-9f67-71242763e0fa.jpg)

**Comment by tmcelrath** [comment]
These are two examples of the slide sheets we need parsed. The bottom one is a typical slide sheet. The top one was how many ticks, lice, and Collembola vials had their labels scanned. Both types will need to be parsed.

**Comment by jrflood** [comment]
Images have been used extensively in development and debugging.
