### ISSUE TITLE
As a developer I need a method to scale line coordinates

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/sled#11]

**Comment by jrflood** [comment]
The working definition of this is that the successor image may be of differing pixel dimensions, and so the separation lines should stretch or shrink to that of the new image.

**Comment by jrflood** [comment]
Imposing the restriction that demarkation lines are strictly horizontal or vertical implies that the orthogonal coordinate is irrelevant.  That is, a horizontal line can be described as y = 28.  Similarly, a vertical line would be x = 40.  Possible reduction in structure for sled image object representation.
Therefore, the computation over lines would reduce to (new ordinal value) = (old ordinal value) * (new image ordinal extent) / (old image ordinal extent).  This operation would range over both horizontal and vertical ordinal dimensions.

**Comment by jrflood** [comment]
Based on previous recent development, it is hypothesized that the scaling of horizontal and vertical lines can be done independently.  That is, when either image dimension changes, that corresponding set of lines is recalculated.  If both dimensions are changed, as in a new image is obtained, then each dimension's lines can be calculated in either order, then  the cells calculated from the new line coordinates.

**Comment by jrflood** [comment]
This functionality is accomplished through the method resizeImage in app.vue.  When reading a new image, the app invokes this method, repositioning the lines based on the difference in image dimensions.
