### ISSUE TITLE
As a developer I need a method to translate line coordinates

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/sled#12]

**Comment by jrflood** [comment]
This is to position/reposition horizontal and vertical boundary lines for an image partitioning overlay grid.  This is to be effected through the user interface primarily.

**Comment by jrflood** [comment]
This functionality is obliquely referenced in #14.  The presumed method is to drag one of the control points to position the line in its new position.  Additional articulation will be required to change the length of a line.

**Comment by jrflood** [comment]
Initial arrangement of lines
![Screen Shot 2019-05-23 at 10 18 52 AM](https://user-images.githubusercontent.com/5349955/58265048-90142c00-7d44-11e9-82d7-2fb6277a455a.png)
Move top line down
![Screen Shot 2019-05-23 at 10 22 18 AM](https://user-images.githubusercontent.com/5349955/58265101-ab7f3700-7d44-11e9-98f8-e0a5ac61a242.png)
Move leftmost line to right
![Screen Shot 2019-05-23 at 10 23 08 AM](https://user-images.githubusercontent.com/5349955/58265166-c94c9c00-7d44-11e9-8b24-f703e2a85677.png)

**Comment by jrflood** [comment]
This function devolves to the low level methods moveV and moveH(index, offset) in app.vue.  The offset is in pixels, and the index is that of the line in its respective array.

**Comment by jrflood** [comment]
Grid move is now refactored to use moveV and moveH iteratively.
