### ISSUE TITLE
As a developer I need to determine how image coordinates will be derived from lines of a certain pixel width

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/sled#13]

**Comment by jrflood** [comment]
Image coordinates are relative within a section and will have origin [0, 0] in pixels at the upper left corner.  The selection of pixels would be bounded by the lines' centers.  Care must be taken to properly handle the fact that lines are commonly shared between sections.  Formal expression of the calculation will follow.

**Comment by jrflood** [comment]
Contrary to the title, the width of the lines has been made independent of the derived coordinates, with the width being primarily a function of visibility vis a vis the overlaid image.

**Comment by jrflood** [comment]
No rationale for modifying the conclusion reached circa May 2.  Line pixel width is a user interface attribute which does not affect image coordinate calculation.
