### ISSUE TITLE
As a developer I need a variable to control line width

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/sled#14]

**Comment by jrflood** [comment]
Line width is envisioned to be an exclusionary attribute to isolate rectangular pixel zones.  Should there be separate horizontal and vertical widths?

**Comment by mjy** [comment]
No, I don't think so, the width will largely be so people can see the lines.

**Comment by jrflood** [comment]
OK, so the barriers in the image are not to be masked by the lines, and will be included in the image segments...?

**Comment by mjy** [comment]
How about posting a screenshot to express the question so we're sure we are on the same page?

**Comment by jrflood** [comment]
![Screen Shot 2019-05-01 at 1 28 30 PM](https://user-images.githubusercontent.com/5349955/57034409-0a093780-6c15-11e9-91f1-247ae055efb7.png)

**Comment by jrflood** [comment]
app.vue method data variable lineThickness is used to set thickness (stroke-width) for SVG lines.  The form has an input for this value.
