### ISSUE TITLE
As a developer I need a JSON representation of the coordinates of the slides

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/sled#2]

**Comment by jrflood** [comment]
Copied from issue #7: The JSON for the line coordinates is an array of cells defined by the the intersections of vertical and horizontal lines. Each cell is an array of coordinates specifying the upper left and lower right corners of the rectangular cell as [x, y] pixel coordinates. For example:
"[[[150,50],[2056,687]],[[2056,50],[3952,687]],[[150,687],[2056,1464]],[[2056,687],[3952,1464]],[[150,1464],[2056,2056]],[[2056,1464],[3952,2056]]]"
denotes six cells ranging over a 5028x6935 image from [150, 50] to [3952, 1464]. The cell[0] is [[150,50],[2056,687]], cell[3] is [[2056,687],[3952,1464]], etc.
