### ISSUE TITLE
As a user I want to assign a metadata class to boxes that are unselected

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/sled#25]
When I uncheck a box, then if `metadata_assignment` is populated a combination bar appears in the center of the box. 
```
<sled-component
  :vertical-lines="vlines"
  :horizontal-lines="hlines"
  :metadata_assignment="{'key' => 'value', 'key2' => 'value2'}"
...
  @onComputeCells="saveCells"/>
```
* `:metadata_assignment="{'key' => 'value', 'key2' => 'value2'}"`.  Not sure of the structure, likely a JSON string, or maybe a native structure?
* [ ] Always add an "Empty" option, that is defaulted to.

<img width="1291" alt="Screen Shot 2020-01-08 at 10 50 00 AM" src="https://user-images.githubusercontent.com/22600/71998130-b23fb900-3204-11ea-9f7f-5522e321e549.png">

**Comment by jlpereira** [comment]
Done
