### ISSUE TITLE
As a developer I need a specification for how lines can be moved

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/sled#5]

**Comment by jrflood** [comment]
Preparation for moving existing lines. Provide bubbles for exposure on mouseover.  Mousedown on bubble drags bubble affecting coordinate(s).  For horizontal and vertical lines, only their respective coordinate is affected.  For the upper left corner bubble, both dimensions are changed to reposition the entire grid of lines.  For the lower right bubble, the line coordinates are stretched or shrunk linearly across the extent of the line sets.

**Comment by jrflood** [comment]
![Screen Shot 2019-06-19 at 9 47 08 AM](https://user-images.githubusercontent.com/5349955/59775721-3fc2b800-9277-11e9-88aa-e0b730d8a268.png)

**Comment by jrflood** [comment]
Basic functionality of the grid drag and stretch bubble targets is largely accomplished.  There are some issues related to performance, in that it is fairly easy to outrun the target bubble with the mouse.  This has the effect of leaving the grid frozen until the mouse is over the target again, and there is loss of the interaction state (i.e., mouseup might occur but is not detected).  May need more listeners for mouseout/mouseleave/etc., but basically performance is a bit sluggish.

**Comment by jrflood** [comment]
Some user awkwardness remains in dragging bubbles, but gross behavior is generally correct as follows:
mouseover a line, and a drag bubble appears at 30% of line length; drag the bubble orthogonally to the line and the line is relocated.  Individual drag bubbles are black and are removed 2 seconds after instantiation.  Corner (UL, LR) bubbles are red, and always present. UL bubble drags the entire grid of cells, LR stretches or shrinks entire grid proportionally.  Some tuning is needed to maintain continuity in dragging and stability of line drag bubbles.

**Comment by jrflood** [comment]
Lines are moved ultimately by the primitive methods moveV and moveH(index, offset).  The user interface page uses various buttons and drag bubbles to pass parameters to these methods.
