### ISSUE TITLE
As a developer I need a specification for how line coordinates can be stored as JSON

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/sled#7]
This is in contrast to how the image coordinates are derived from this line placement.

**Comment by jrflood** [comment]
Need a mechanism to carry forward the previous image/line state.

**Comment by jrflood** [comment]
The JSON for the line coordinates is an array of cells defined by the the intersections of vertical and horizontal lines.  Each cell is an array of coordinates specifying the upper left and lower right corners of the rectangular cell as [x, y] pixel coordinates. For example:
"[[[150,50],[2056,687]],[[2056,50],[3952,687]],[[150,687],[2056,1464]],[[2056,687],[3952,1464]],[[150,1464],[2056,2056]],[[2056,1464],[3952,2056]]]"
 denotes six cells ranging over a 5028x6935 image from [150, 50] to [3952, 1464].  The cell[0] is [[150,50],[2056,687]], cell[3] is [[2056,687],[3952,1464]], etc.
