### ISSUE TITLE
As a developer I need sample line data in JSON format for testing purposes

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/sled#9]

**Comment by jrflood** [comment]
Sample line data from first sample image provided in issue #1 (8 cells; 2 columns, 4 rows):
"[[[125,25],[2023,707]],[[2023,25],[3920,707]],[[125,707],[2023,1389]],[[2023,707],[3920,1389]],[[125,1389],[2023,2070]],[[2023,1389],[3920,2070]],[[125,2070],[2023,2752]],[[2023,2070],[3920,2752]]]"
A method in app.vue, generateJSON() is invoked by a button input on the form and presents the current line grid cells as JSON.
